create materialized view persoon.vertrek_aangehaakt_sas as
select
	*,
	coalesce(nwegem, lndemi) as migrln
from
	(select
		jaar,
		anummr,
		bsnumm,
		unicod,
		gslcha,
		lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
		gebpla,
		bevcbs,
		etncbs,
		lpad(natiob::char(3), 3, '0')::char(3) as natiob,
		vstdgr,
		vstdta,
		vstned,
		brgstb,
		codvbt,
		dathuw,
		dathon,
		dtbvbt,
		dtevbt,
		gbdtb8,
		leeftd,
		leeft1,
		lpad(hhtypev::char(2), 2, '0')::char(2) as hhtypev,
		uniou1,
		uniou2,
		gslou1,
		gslou2,
		lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
		lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
		gbdou1,
		gbdou2,
		huisnv,
		huislv,
		hstoev,
		ptkodv,
		lpad(nwegem::char(4), 4, '0')::char(4) as nwegem,
		NULL::char(4) as lndemi,
		geldig_op,
		tydber,
		adrs15v,
		stkodv,
		lpad(bagidsv::char(16), 16, '0')::char(16) as bagidsv,
		lpad(numidsv::char(16), 16, '0')::char(16) as numidsv,
		coalesce(brtk15v, 'Z99z') as brtk15v,
		coalesce(bctk15v, 'Z99') as bctk15v,
		coalesce(stad15v, 'Z') as stad15v,
		coalesce(i22gebv, 'ZX99') as i22gebv,
		coalesce(i27gebv, 'ZY99') as i27gebv,
		coalesce(altbrt15v, 'ZS99') as altbrt15v,
		coalesce(rayon15v, 'ZA99') as rayon15v,
		coalesce(brtk10v, 'Z99z') as brtk10v,
		'vertrek binnenland'::char(20) as hfdkod
	from
		persoon.vertrek_binnenland_aangehaakt_adres
	union all
	select
		jaar,
		anummr,
		bsnumm,
		unicod,
		gslcha,
		lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
		gebpla,
		bevcbs,
		etncbs,
		lpad(natiob::char(3), 3, '0')::char(3) as natiob,
		vstdgr,
		vstdta,
		vstned,
		brgstb,
		codvbt,
		dathuw,
		dathon,
		dtbvbt,
		dtevbt,
		gbdtb8,
		leeftd,
		leeft1,
		lpad(hhtypev::char(2), 2, '0')::char(2) as hhtypev,
		uniou1,
		uniou2,
		gslou1,
		gslou2,
		lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
		lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
		gbdou1,
		gbdou2,
		huisnv,
		huislv,
		hstoev,
		ptkodv,
		lpad(nwegem::char(4), 4, '0')::char(4) as nwegem,
		NULL::char(4) as lndemi,
		geldig_op,
		tydber,
		adrs15v,
		stkodv,
		lpad(bagidsv::char(16), 16, '0')::char(16) as bagidsv,
		lpad(numidsv::char(16), 16, '0')::char(16) as numidsv,
		coalesce(brtk15v, 'Z99z') as brtk15v,
		coalesce(bctk15v, 'Z99') as bctk15v,
		coalesce(stad15v, 'Z') as stad15v,
		coalesce(i22gebv, 'ZX99') as i22gebv,
		coalesce(i27gebv, 'ZY99') as i27gebv,
		coalesce(altbrt15v, 'ZS99') as altbrt15v,
		coalesce(rayon15v, 'ZA99') as rayon15v,
		coalesce(brtk10v, 'Z99z') as brtk10v,
		'vertrek binnenland'::char(20) as hfdkod
	from
		persoon.vertrek_binnenland_aangehaakt_adres1
	union all
	select
		jaar,
		anummr,
		bsnumm,
		unicod,
		gslcha,
		lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
		gebpla,
		bevcbs,
		etncbs,
		lpad(natiob::char(3), 3, '0')::char(3) as natiob,
		vstdgr,
		vstdta,
		vstned,
		brgstb,
		codvbt,
		dathuw,
		dathon,
		dtbvbt,
		dtevbt,
		gbdtb8,
		leeftd,
		leeft1,
		lpad(hhtypev::char(2), 2, '0')::char(2) as hhtypev,
		uniou1,
		uniou2,
		gslou1,
		gslou2,
		lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
		lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
		gbdou1,
		gbdou2,
		huisnv,
		huislv,
		hstoev,
		ptkodv,
		NULL::char(4) as nwegem,
		lpad(lndemi::char(4), 4,'0')::char(4) as lndemi,
		geldig_op,
		tydber,
		adrs15v,
		stkodv,
		lpad(bagidsv::char(16), 16, '0')::char(16) as bagidsv,
		lpad(numidsv::char(16), 16, '0')::char(16) as numidsv,
		coalesce(brtk15v, 'Z99z') as brtk15v,
		coalesce(bctk15v, 'Z99') as bctk15v,
		coalesce(stad15v, 'Z') as stad15v,
		coalesce(i22gebv, 'ZX99') as i22gebv,
		coalesce(i27gebv, 'ZY99') as i27gebv,
		coalesce(altbrt15v, 'ZS99') as altbrt15v,
		coalesce(rayon15v, 'ZA99') as rayon15v,
		coalesce(brtk10v, 'Z99z') as brtk10v,
		'vertrek buitenland'::char(20) as hfdkod
	from
		persoon.vertrek_buitenland_aangehaakt_adres
	union all
	select
		jaar,
		anummr,
		bsnumm,
		unicod,
		gslcha,
		lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
		gebpla,
		bevcbs,
		etncbs,
		lpad(natiob::char(3), 3, '0')::char(3) as natiob,
		vstdgr,
		vstdta,
		vstned,
		brgstb,
		codvbt,
		dathuw,
		dathon,
		dtbvbt,
		dtevbt,
		gbdtb8,
		leeftd,
		leeft1,
		lpad(hhtypev::char(2), 2, '0')::char(2) as hhtypev,
		uniou1,
		uniou2,
		gslou1,
		gslou2,
		lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
		lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
		gbdou1,
		gbdou2,
		huisnv,
		huislv,
		hstoev,
		ptkodv,
		NULL::char(4) as nwegem,
		lpad(lndemi::char(4), 4,'0')::char(4) as lndemi,
		geldig_op,
		tydber,
		adrs15v,
		stkodv,
		lpad(bagidsv::char(16), 16, '0')::char(16) as bagidsv,
		lpad(numidsv::char(16), 16, '0')::char(16) as numidsv,
		coalesce(brtk15v, 'Z99z') as brtk15v,
		coalesce(bctk15v, 'Z99') as bctk15v,
		coalesce(stad15v, 'Z') as stad15v,
		coalesce(i22gebv, 'ZX99') as i22gebv,
		coalesce(i27gebv, 'ZY99') as i27gebv,
		coalesce(altbrt15v, 'ZS99') as altbrt15v,
		coalesce(rayon15v, 'ZA99') as rayon15v,
		coalesce(brtk10v, 'Z99z') as brtk10v,
		'vertrek buitenland'::char(20) as hfdkod
	from
		persoon.vertrek_buitenland_aangehaakt_adres1
	) as a