create materialized view persoon.vestiging_aangehaakt_sas as
select
	*,
	coalesce(vorgem, lndimm) as migrlv
from (
	select
		jaar,
		anummr,
		bsnumm,
		unicod,
		gslcha,
		lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
		gebpla,
		bevcbs,
		etncbs,
		lpad(natiob::char(3), 3, '0')::char(3) as natiob,
		vstdgr,
		vstdta,
		vstned,
		brgstb,
		codvbt,
		dathuw,
		dathon,
		dtbvbt,
		dtevbt,
		gbdtb8,
		leeftd,
		leeft1,
		lpad(hhtypen::char(2), 2, '0')::char(2) as hhtypen,
		uniou1,
		uniou2,
		gslou1,
		gslou2,
		lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
		lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
		gbdou1,
		gbdou2,
		huisnn,
		huisln,
		hstoen,
		ptkodn,
		geldig_op,
		tydber,
		adrs15n,
		stkodn,
		lpad(bagidsn::char(16), 16, '0')::char(16) as bagidsn,
		lpad(numidsn::char(16), 16, '0')::char(16) as numidsn,
		coalesce(brtk15n, 'Z99z') as brtk15n,
		coalesce(bctk15n, 'Z99') as bctk15n,
		coalesce(stad15n, 'Z') as stad15n,
		coalesce(i22gebn, 'ZX99') as i22gebn,
		coalesce(i27gebn, 'ZY99') as i27gebn,
		coalesce(altbrt15n, 'ZS99') as altbrt15n,
		coalesce(rayon15n, 'ZA99') as rayon15n,
		coalesce(brtk10n, 'Z99z') as brtk10n,
		lpad(vorgem::char(4), 4, '0')::char(4) as vorgem,
		lpad(lndimm::char(4), 4, '0')::char(4) as lndimm
	from
		persoon.vestiging_aangehaakt_adres
	union all
	select
		jaar,
		anummr,
		bsnumm,
		unicod,
		gslcha,
		lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
		gebpla,
		bevcbs,
		etncbs,
		lpad(natiob::char(3), 3, '0')::char(3) as natiob,
		vstdgr,
		vstdta,
		vstned,
		brgstb,
		codvbt,
		dathuw,
		dathon,
		dtbvbt,
		dtevbt,
		gbdtb8,
		leeftd,
		leeft1,
		lpad(hhtypen::char(2), 2, '0')::char(2) as hhtypen,
		uniou1,
		uniou2,
		gslou1,
		gslou2,
		lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
		lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
		gbdou1,
		gbdou2,
		huisnn,
		huisln,
		hstoen,
		ptkodn,
		geldig_op,
		tydber,
		adrs15n,
		stkodn,
		lpad(bagidsn::char(16), 16, '0')::char(16) as bagidsn,
		lpad(numidsn::char(16), 16, '0')::char(16) as numidsn,
		coalesce(brtk15n, 'Z99z') as brtk15n,
		coalesce(bctk15n, 'Z99') as bctk15n,
		coalesce(stad15n, 'Z') as stad15n,
		coalesce(i22gebn, 'ZX99') as i22gebn,
		coalesce(i27gebn, 'ZY99') as i27gebn,
		coalesce(altbrt15n, 'ZS99') as altbrt15n,
		coalesce(rayon15n, 'ZA99') as rayon15n,
		coalesce(brtk10n, 'Z99z') as brtk10n,
		lpad(vorgem::char(4), 4, '0')::char(4) as vorgem,
		lpad(lndimm::char(4), 4, '0')::char(4) as lndimm
	from
		persoon.vestiging_aangehaakt_adres1
	) as a