--
-- +/- 30min
--
create or replace function verhuizing_aangehaakt_adres()
returns table (
	jaar integer,
	anummr bigint,
	bsnumm bigint,
	unicod bigint,
	gslcha character varying,
	lndgbb bigint,
	gebpla character varying,
	bevcbs bigint,
	etncbs bigint,
	natiob bigint,
	vstdgr bigint,
	vstdta bigint,
	vstned bigint,
	brgstb bigint,
	codvbt integer,
	dathuw bigint,
	dathon bigint,
	dtbvbt bigint,
	dtevbt bigint,
	gbdtb8 bigint,
	leeftd double precision,
	leeft1 double precision,
	hhtypen bigint,
	uniou1 bigint,
	uniou2 bigint,
	gslou1 character varying,
	gslou2 character varying,
	gblou1 bigint,
	gblou2 bigint,
	gbdou1 bigint,
	gbdou2 bigint,
	stkodv bigint,
	huisnv integer,
	huislv character,
	hstoev character varying,
	ptkodv character,
	adrs15v text,
	stkodn bigint,
	huisnn integer,
	huisln bpchar,
	hstoen character varying,
	ptkodn character,
	adrs15n text,
	geldig_op integer,
	tydber integer,
	bagidsn bigint,
	numidsn bigint,
	brtk15n text,
	bctk15n text,
	stad15n text,
	i22gebn character varying,
	i27gebn character varying,
	altbrt15n character varying,
	rayon15n character varying,
	brtk10n character varying
) as $$

select
	distinct on(a.anummr, a.bsnumm, a.geldig_op)
	a.jaar,
	a.anummr,
	a.bsnumm,
	a.unicod,
	a.gslcha,
	a.lndgbb,
	a.gebpla,
	a.bevcbs,
	a.etncbs,
	a.natiob,
	a.vstdgr,
	a.vstdta,
	a.vstned,
	a.brgstb,
	a.codvbt,
	a.dathuw,
	a.dathon,
	a.dtbvbt,
	a.dtevbt,
	a.gbdtb8,
	a.leeftd,
	a.leeft1,
	a.hhtypen,
	a.uniou1,
	a.uniou2,
	a.gslou1,
	a.gslou2,
	a.gblou1,
	a.gblou2,
	a.gbdou1,
	a.gbdou2,
	a.stkodv,
	a.huisnv,
	a.huislv,
	a.hstoev,
	a.ptkodv,
	a.adrs15v,
	a.stkodn,
	a.huisnn,
	a.huisln,
	a.hstoen,
	case when a.ptkodn is null and g.postcode is not null then
		g.postcode
	else
		a.ptkodn
	end as ptkodn,
	a.adrs15n,
	a.geldig_op,
	a.tydber,
	g.object_id as bagidsn,
	g.nummer_id as numidsn,
	g.buurtcode as brtk15n,
	substring(g.buurtcode, 1, 3) as bctk15n,
	substring(g.buurtcode, 1, 1) as stad15n,
	(select i22geb from bron.kwadrs where brtk15 = g.buurtcode and i22geb is not null order by kwartaal desc limit 1) as i22gebn,
	(select i27geb from bron.kwadrs where brtk15 = g.buurtcode and i27geb is not null order by kwartaal desc limit 1) as i27gebn,
	(select altbrt15 from bron.kwadrs where brtk15 = g.buurtcode and altbrt15 is not null order by kwartaal desc limit 1) as altbrt15n,
	(select rayon15 from bron.kwadrs where brtk15 = g.buurtcode and rayon15 is not null order by kwartaal desc limit 1) as rayon15n,
	(select brtk10 from bron.kwadrs as k where k.pttkod = a.ptkodn and k.huisnr = a.huisnn and coalesce(k.huislt, '-') = coalesce(a.huisln, '-') and k.brtk10 is not null order by k.kwartaal desc limit 1) as brtk10n
from
	persoon.verhuizing_aangehaakt as a
left join lateral
	geef_bag_informatie_voor_adres(a.ptkodn, a.stkodn, a.huisnn, a.huisln, a.hstoen, a.geldig_op::char(8)::timestamp without time zone) as g
on true
order by
	a.anummr, a.bsnumm, a.geldig_op;

$$ language sql;