--
-- +/- 30min
--
create or replace function verhuizing_aangehaakt_adres1()
returns table (
	jaar integer,
	anummr bigint,
	bsnumm bigint,
	unicod bigint,
	gslcha character varying,
	lndgbb bigint,
	gebpla character varying,
	bevcbs bigint,
	etncbs bigint,
	natiob bigint,
	vstdgr bigint,
	vstdta bigint,
	vstned bigint,
	brgstb bigint,
	codvbt integer,
	dathuw bigint,
	dathon bigint,
	dtbvbt bigint,
	dtevbt bigint,
	gbdtb8 bigint,
	leeftd double precision,
	leeft1 double precision,
	hhtypen bigint,
	uniou1 bigint,
	uniou2 bigint,
	gslou1 character varying,
	gslou2 character varying,
	gblou1 bigint,
	gblou2 bigint,
	gbdou1 bigint,
	gbdou2 bigint,
	stkodv bigint,
	huisnv integer,
	huislv character,
	hstoev character varying,
	ptkodv character,
	adrs15v text,
	stkodn bigint,
	huisnn integer,
	huisln bpchar,
	hstoen character varying,
	ptkodn character,
	adrs15n text,
	geldig_op integer,
	tydber integer,
	bagidsn  bigint,
	numidsn bigint,
	brtk15n text,
	bctk15n text,
	stad15n text,
	i22gebn character varying,
	i27gebn character varying,
	altbrt15n character varying,
	rayon15n character varying,
	brtk10n character varying,
	bagidsv bigint,
	numidsv bigint,
	brtk15v text,
	bctk15v	text,
	stad15v	text,
	i22gebv character varying,
	i27gebv character varying,
	altbrt15v character varying,
	rayon15v character varying,
	brtk10v character varying
) as $$

select
	distinct on(a.anummr, a.bsnumm, a.geldig_op)
	a.jaar,
	a.anummr,
	a.bsnumm,
	a.unicod,
	a.gslcha,
	a.lndgbb,
	a.gebpla,
	a.bevcbs,
	a.etncbs,
	a.natiob,
	a.vstdgr,
	a.vstdta,
	a.vstned,
	a.brgstb,
	a.codvbt,
	a.dathuw,
	a.dathon,
	a.dtbvbt,
	a.dtevbt,
	a.gbdtb8,
	a.leeftd,
	a.leeft1,
	a.hhtypen,
	a.uniou1,
	a.uniou2,
	a.gslou1,
	a.gslou2,
	a.gblou1,
	a.gblou2,
	a.gbdou1,
	a.gbdou2,
	a.stkodv,
	a.huisnv,
	a.huislv,
	a.hstoev,
	case when a.ptkodv is null and g.postcode is not null then
		g.postcode
	else
		a.ptkodv
	end as ptkodv,
	a.adrs15v,
	a.stkodn,
	a.huisnn,
	a.huisln,
	a.hstoen,
	a.ptkodn,
	a.adrs15n,
	a.geldig_op,
	a.tydber,
	a.bagidsn,
	a.numidsn,
	a.brtk15n,
	a.bctk15n,
	a.stad15n,
	a.i22gebn,
	a.i27gebn,
	a.altbrt15n,
	a.rayon15n,
	a.brtk10n,
	g.object_id as bagidsv,
	g.nummer_id as numidsv,
	g.buurtcode as brtk15v,
	substring(g.buurtcode, 1, 3) as bctk15v,
	substring(g.buurtcode, 1, 1) as stad15v,
	(select i22geb from bron.kwadrs where brtk15 = g.buurtcode and i22geb is not null order by kwartaal desc limit 1) as i22gebv,
	(select i27geb from bron.kwadrs where brtk15 = g.buurtcode and i27geb is not null order by kwartaal desc limit 1) as i27gebv,
	(select altbrt15 from bron.kwadrs where brtk15 = g.buurtcode and altbrt15 is not null order by kwartaal desc limit 1) as altbrt15v,
	(select rayon15 from bron.kwadrs where brtk15 = g.buurtcode and rayon15 is not null order by kwartaal desc limit 1) as rayon15v,
	(select brtk10 from bron.kwadrs as k where k.pttkod = a.ptkodv and k.huisnr = a.huisnv and coalesce(k.huislt, '-') = coalesce(a.huislv, '-') and k.brtk10 is not null order by k.kwartaal desc limit 1) as brtk10v
from
	persoon.verhuizing_aangehaakt_adres as a
left join lateral
	geef_bag_informatie_voor_adres(a.ptkodv, a.stkodv, a.huisnv, a.huislv, a.hstoev, a.geldig_op::char(8)::timestamp without time zone) as g
on true
order by
	a.anummr, a.bsnumm, a.geldig_op;

$$ language sql;